// Copyright 2022 Trukhanov Artem
#ifndef MODULES_TRUKHANOV_ARTEM_EULER_FUNCTION_INCLUDE_EULER_FUNCTION_H_
#define MODULES_TRUKHANOV_ARTEM_EULER_FUNCTION_INCLUDE_EULER_FUNCTION_H_

class EulerFunction {
 public:
  static int Calculate(int number);
};

#endif  // MODULES_TRUKHANOV_ARTEM_EULER_FUNCTION_INCLUDE_EULER_FUNCTION_H_
